name: Terraform Plan

on:
  push:  
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      # pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE }}
      #     role-session-name: GitHubActions
      #     aws-region: eu-north-1

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Generate Terraform Plan
        run: |
          cd terraform
          terraform plan -var-file="dev.tfvars" -out=tfplan
          terraform apply -var-file="dev.tfvars" --auto-approve

        #terraform destroy -var-file="dev.tfvars" --auto-approve
        